### ISSUE TITLE
MacOS: Failed to build pycrypto

### ISSUE THREAD

**Issue by gMan1990** [cshuaimin/video-funnel#14]
- MacOS Mojave 10.14.6
- pip 19.1.1 from /usr/local/lib/python3.7

```text
Building wheels for collected packages: pycrypto
  Building wheel for pycrypto (setup.py) ... error
  ERROR: Complete output from command /usr/local/opt/python/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/2t/wl5pwd7n6_q76yxrdb5bhl_r0000gn/T/pip-install-ulks_dv5/pycrypto/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/2t/wl5pwd7n6_q76yxrdb5bhl_r0000gn/T/pip-wheel-886_nwyg --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.13-x86_64-3.7
  creating build/lib.macosx-10.13-x86_64-3.7/Crypto
  copying lib/Crypto/pct_warnings.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto
  copying lib/Crypto/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto
  creating build/lib.macosx-10.13-x86_64-3.7/Crypto/Hash
  copying lib/Crypto/Hash/MD2.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Hash
  copying lib/Crypto/Hash/SHA512.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Hash
  copying lib/Crypto/Hash/SHA384.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Hash
  copying lib/Crypto/Hash/SHA256.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Hash
  copying lib/Crypto/Hash/hashalgo.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Hash
  copying lib/Crypto/Hash/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Hash
  copying lib/Crypto/Hash/SHA.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Hash
  copying lib/Crypto/Hash/SHA224.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Hash
  copying lib/Crypto/Hash/MD4.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Hash
  copying lib/Crypto/Hash/HMAC.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Hash
  copying lib/Crypto/Hash/MD5.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Hash
  copying lib/Crypto/Hash/RIPEMD.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Hash
  creating build/lib.macosx-10.13-x86_64-3.7/Crypto/Cipher
  copying lib/Crypto/Cipher/CAST.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Cipher
  copying lib/Crypto/Cipher/ARC4.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Cipher
  copying lib/Crypto/Cipher/AES.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Cipher
  copying lib/Crypto/Cipher/PKCS1_v1_5.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Cipher
  copying lib/Crypto/Cipher/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Cipher
  copying lib/Crypto/Cipher/DES3.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Cipher
  copying lib/Crypto/Cipher/XOR.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Cipher
  copying lib/Crypto/Cipher/Blowfish.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Cipher
  copying lib/Crypto/Cipher/ARC2.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Cipher
  copying lib/Crypto/Cipher/PKCS1_OAEP.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Cipher
  copying lib/Crypto/Cipher/DES.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Cipher
  copying lib/Crypto/Cipher/blockalgo.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Cipher
  creating build/lib.macosx-10.13-x86_64-3.7/Crypto/Util
  copying lib/Crypto/Util/py3compat.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Util
  copying lib/Crypto/Util/number.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Util
  copying lib/Crypto/Util/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Util
  copying lib/Crypto/Util/winrandom.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Util
  copying lib/Crypto/Util/_number_new.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Util
  copying lib/Crypto/Util/RFC1751.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Util
  copying lib/Crypto/Util/randpool.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Util
  copying lib/Crypto/Util/Counter.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Util
  copying lib/Crypto/Util/asn1.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Util
  creating build/lib.macosx-10.13-x86_64-3.7/Crypto/Random
  copying lib/Crypto/Random/_UserFriendlyRNG.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Random
  copying lib/Crypto/Random/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Random
  copying lib/Crypto/Random/random.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Random
  creating build/lib.macosx-10.13-x86_64-3.7/Crypto/Random/Fortuna
  copying lib/Crypto/Random/Fortuna/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Random/Fortuna
  copying lib/Crypto/Random/Fortuna/SHAd256.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Random/Fortuna
  copying lib/Crypto/Random/Fortuna/FortunaGenerator.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Random/Fortuna
  copying lib/Crypto/Random/Fortuna/FortunaAccumulator.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Random/Fortuna
  creating build/lib.macosx-10.13-x86_64-3.7/Crypto/Random/OSRNG
  copying lib/Crypto/Random/OSRNG/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Random/OSRNG
  copying lib/Crypto/Random/OSRNG/posix.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Random/OSRNG
  copying lib/Crypto/Random/OSRNG/rng_base.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Random/OSRNG
  copying lib/Crypto/Random/OSRNG/fallback.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Random/OSRNG
  creating build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest
  copying lib/Crypto/SelfTest/st_common.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest
  copying lib/Crypto/SelfTest/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest
  creating build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Cipher
  copying lib/Crypto/SelfTest/Cipher/test_AES.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Cipher
  copying lib/Crypto/SelfTest/Cipher/test_CAST.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Cipher
  copying lib/Crypto/SelfTest/Cipher/test_ARC4.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Cipher
  copying lib/Crypto/SelfTest/Cipher/test_pkcs1_oaep.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Cipher
  copying lib/Crypto/SelfTest/Cipher/test_DES3.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Cipher
  copying lib/Crypto/SelfTest/Cipher/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Cipher
  copying lib/Crypto/SelfTest/Cipher/common.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Cipher
  copying lib/Crypto/SelfTest/Cipher/test_DES.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Cipher
  copying lib/Crypto/SelfTest/Cipher/test_ARC2.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Cipher
  copying lib/Crypto/SelfTest/Cipher/test_Blowfish.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Cipher
  copying lib/Crypto/SelfTest/Cipher/test_XOR.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Cipher
  copying lib/Crypto/SelfTest/Cipher/test_pkcs1_15.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Cipher
  creating build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Hash
  copying lib/Crypto/SelfTest/Hash/test_SHA224.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Hash
  copying lib/Crypto/SelfTest/Hash/test_MD2.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Hash
  copying lib/Crypto/SelfTest/Hash/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Hash
  copying lib/Crypto/SelfTest/Hash/test_RIPEMD.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Hash
  copying lib/Crypto/SelfTest/Hash/test_MD4.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Hash
  copying lib/Crypto/SelfTest/Hash/common.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Hash
  copying lib/Crypto/SelfTest/Hash/test_SHA512.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Hash
  copying lib/Crypto/SelfTest/Hash/test_MD5.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Hash
  copying lib/Crypto/SelfTest/Hash/test_SHA384.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Hash
  copying lib/Crypto/SelfTest/Hash/test_SHA.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Hash
  copying lib/Crypto/SelfTest/Hash/test_SHA256.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Hash
  copying lib/Crypto/SelfTest/Hash/test_HMAC.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Hash
  creating build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Protocol
  copying lib/Crypto/SelfTest/Protocol/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Protocol
  copying lib/Crypto/SelfTest/Protocol/test_AllOrNothing.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Protocol
  copying lib/Crypto/SelfTest/Protocol/test_rfc1751.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Protocol
  copying lib/Crypto/SelfTest/Protocol/test_chaffing.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Protocol
  copying lib/Crypto/SelfTest/Protocol/test_KDF.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Protocol
  creating build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/PublicKey
  copying lib/Crypto/SelfTest/PublicKey/test_RSA.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/PublicKey
  copying lib/Crypto/SelfTest/PublicKey/test_importKey.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/PublicKey
  copying lib/Crypto/SelfTest/PublicKey/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/PublicKey
  copying lib/Crypto/SelfTest/PublicKey/test_DSA.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/PublicKey
  copying lib/Crypto/SelfTest/PublicKey/test_ElGamal.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/PublicKey
  creating build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Random
  copying lib/Crypto/SelfTest/Random/test_rpoolcompat.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Random
  copying lib/Crypto/SelfTest/Random/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Random
  copying lib/Crypto/SelfTest/Random/test_random.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Random
  copying lib/Crypto/SelfTest/Random/test__UserFriendlyRNG.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Random
  creating build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Random/Fortuna
  copying lib/Crypto/SelfTest/Random/Fortuna/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Random/Fortuna
  copying lib/Crypto/SelfTest/Random/Fortuna/test_FortunaGenerator.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Random/Fortuna
  copying lib/Crypto/SelfTest/Random/Fortuna/test_FortunaAccumulator.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Random/Fortuna
  copying lib/Crypto/SelfTest/Random/Fortuna/test_SHAd256.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Random/Fortuna
  creating build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Random/OSRNG
  copying lib/Crypto/SelfTest/Random/OSRNG/test_posix.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Random/OSRNG
  copying lib/Crypto/SelfTest/Random/OSRNG/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Random/OSRNG
  copying lib/Crypto/SelfTest/Random/OSRNG/test_generic.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Random/OSRNG
  copying lib/Crypto/SelfTest/Random/OSRNG/test_fallback.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Random/OSRNG
  copying lib/Crypto/SelfTest/Random/OSRNG/test_nt.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Random/OSRNG
  copying lib/Crypto/SelfTest/Random/OSRNG/test_winrandom.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Random/OSRNG
  creating build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Util
  copying lib/Crypto/SelfTest/Util/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Util
  copying lib/Crypto/SelfTest/Util/test_winrandom.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Util
  copying lib/Crypto/SelfTest/Util/test_Counter.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Util
  copying lib/Crypto/SelfTest/Util/test_asn1.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Util
  copying lib/Crypto/SelfTest/Util/test_number.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Util
  creating build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Signature
  copying lib/Crypto/SelfTest/Signature/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Signature
  copying lib/Crypto/SelfTest/Signature/test_pkcs1_pss.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Signature
  copying lib/Crypto/SelfTest/Signature/test_pkcs1_15.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/SelfTest/Signature
  creating build/lib.macosx-10.13-x86_64-3.7/Crypto/Protocol
  copying lib/Crypto/Protocol/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Protocol
  copying lib/Crypto/Protocol/AllOrNothing.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Protocol
  copying lib/Crypto/Protocol/KDF.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Protocol
  copying lib/Crypto/Protocol/Chaffing.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Protocol
  creating build/lib.macosx-10.13-x86_64-3.7/Crypto/PublicKey
  copying lib/Crypto/PublicKey/_slowmath.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/PublicKey
  copying lib/Crypto/PublicKey/RSA.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/PublicKey
  copying lib/Crypto/PublicKey/pubkey.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/PublicKey
  copying lib/Crypto/PublicKey/_DSA.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/PublicKey
  copying lib/Crypto/PublicKey/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/PublicKey
  copying lib/Crypto/PublicKey/_RSA.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/PublicKey
  copying lib/Crypto/PublicKey/DSA.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/PublicKey
  copying lib/Crypto/PublicKey/ElGamal.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/PublicKey
  creating build/lib.macosx-10.13-x86_64-3.7/Crypto/Signature
  copying lib/Crypto/Signature/PKCS1_PSS.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Signature
  copying lib/Crypto/Signature/PKCS1_v1_5.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Signature
  copying lib/Crypto/Signature/__init__.py -> build/lib.macosx-10.13-x86_64-3.7/Crypto/Signature
  Skipping optional fixer: buffer
  Skipping optional fixer: idioms
  Skipping optional fixer: set_literal
  Skipping optional fixer: ws_comma
  running build_ext
  running build_configure
  checking for gcc... gcc
  checking whether the C compiler works... no
  configure: error: in `/private/var/folders/2t/wl5pwd7n6_q76yxrdb5bhl_r0000gn/T/pip-install-ulks_dv5/pycrypto':
  configure: error: C compiler cannot create executables
  See `config.log' for more details
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/2t/wl5pwd7n6_q76yxrdb5bhl_r0000gn/T/pip-install-ulks_dv5/pycrypto/setup.py", line 456, in <module>
      core.setup(**kw)
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/2t/wl5pwd7n6_q76yxrdb5bhl_r0000gn/T/pip-install-ulks_dv5/pycrypto/setup.py", line 251, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/2t/wl5pwd7n6_q76yxrdb5bhl_r0000gn/T/pip-install-ulks_dv5/pycrypto/setup.py", line 278, in run
      raise RuntimeError("autoconf error")
  RuntimeError: autoconf error
  ----------------------------------------
  ERROR: Failed building wheel for pycrypto
  Running setup.py clean for pycrypto
Failed to build pycrypto
```

**Comment by cshuaimin** [comment]
```
configure: error: C compiler cannot create executables
See `config.log' for more details
```
建议写个 C 的 hello world，然后试试 gcc 能否编译，编译完能否运行。
请自行搜索相关错误信息，或者 `macos install pycrypto` 之类的。
